= Pyramid Secure Response

:pipeline: https://gitlab.com/grauwoelfchen/pyramid_secure_response/badges/master/pipeline.svg
:coverage: https://gitlab.com/grauwoelfchen/pyramid_secure_response/badges/master/coverage.svg
:commit: https://gitlab.com/grauwoelfchen/pyramid_secure_response/commits/master

image:{pipeline}[link="{commit}",title="pipeline status"] image:{coverage}[link="{commit}",title="coverage report"]


`pyramid_secure_response` handles insecure request to provide secure response
(sets HSTS Header, redirects as https).


== Install

[source,bash]
----
$ pip install pyramid_secure_response
----


== Features

`pyramid_secure_response` has 2 tweens.

- SSL Redirect (+http+ request will be redirected as +https+ on same host)
- HSTS Support (The `HTTP Strict Transport Security` header will be added)

And an additional feature.

- Ignore path filter (matched paths with `str.startswith()` will be ignored)


== Usage

=== Setup

==== INI file

like link:https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/paste.html[PasteDeploy] config file.

----
pyramid.includes =
    pyramid_secure_response
----

==== Python

Or you can include in python code.

[source,python]
----
config.include('pyramid_secure_response')
----

It's also available to add tween(s) directly, as you need.

[source,python]
----
config.add_tween('pyramid_secure_response.ssl_redirect.tween')
config.add_tween('pyramid_secure_response.hsts_support.tween')
----

You may want to add also kwargs `under` or `over`. (
See https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.add_tween)

By default, `ssl_redirect` tween will be handled before `hsts_support`.

[source,python]
----
config.add_tween('pyramid_secure_response.ssl_redirect.tween',
                 over=tweens.MAIN)
config.add_tween('pyramid_secure_response.hsts_support.tween',
                 over=tweens.MAIN, under='pyramid_secure_response.ssl_redirect.tween')
----

=== Configuration

For example:

-----
pyramid_secure_response.ssl_redirect = False

pyramid_secure_response.hsts_support = True
pyramid_secure_response.hsts_max_age = 63072000
pyramid_secure_response.hsts_include_subdomains = True
pyramid_secure_response.hsts_preload = True

pyramid_secure_response.proto_header = X-Forwarded-Proto
pyramid_secure_response.ignore_paths =
  /_ah/health
  /internal_api/xx
-----

==== Default values

|====
| Key          | Value (in .ini) | Used As | Note
| ssl_redirect | `'True'` | +bool+ | Enable +ssl_redirect+ tween
| hsts_support | `'True'` | +bool+ | Enable +hsts_support+ tween
| hsts_max_age | `'31536000'` | +str+ | In seconds, Appends `max-age=N` into HSTS Header
| hsts_include_subdomains | `'True'` | +bool+ | Appends `includeSubdomains` into HSTS Header
| hsts_preload | `'True'` | +bool+ | Appends `preload` into HSTS Header
| proto_header | `''` | +str+ | An additional header like `'X-Forwarded-Proto'`. Checked in criteria as `https`, if exists.
| ignore_paths | `''` | +list+ | Splittable string like `'\n/path\n/path\n'`. Skiped, if matched.
|====



== Development

See +Makefile+.

[source,bash]
----
(venv) $ make check
(venv) $ make lint

(venv) $ make test
(venv) $ make coverage
----


== License

BSD 3-Clause "New" or "Revised" License (+BSD-3-Clause+)

See link:LICENSE[].
